FROM python:3

WORKDIR /app

COPY requirements.vault.txt ./
RUN pip install --no-cache-dir -r requirements.vault.txt

COPY . .

RUN sh install-ipfshttpclient.sh

ENV FLASK_APP=vault
ENV FLASK_ENV=development

CMD flask run --host=0.0.0.0
