FROM python:3

WORKDIR /app
RUN pip install python-dateutil python-bitcoinrpc py-cid flit redis flask flask-wtf flask-bootstrap
COPY . .
RUN sh install-ipfshttpclient.sh

ENV FLASK_APP=vault
ENV FLASK_ENV=development

CMD flask run --host=0.0.0.0
